# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.23

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/local/Cellar/cmake/3.23.0/bin/cmake

# The command to remove a file.
RM = /usr/local/Cellar/cmake/3.23.0/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /Users/red_snake/projects/3dengine

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /Users/red_snake/projects/3dengine

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/local/Cellar/cmake/3.23.0/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/local/Cellar/cmake/3.23.0/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/red_snake/projects/3dengine/CMakeFiles /Users/red_snake/projects/3dengine//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/red_snake/projects/3dengine/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named engine

# Build rule for target.
engine: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 engine
.PHONY : engine

# fast build rule for target.
engine/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/engine.dir/build.make CMakeFiles/engine.dir/build
.PHONY : engine/fast

src/FBOShader.o: src/FBOShader.cpp.o
.PHONY : src/FBOShader.o

# target to build an object file
src/FBOShader.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/engine.dir/build.make CMakeFiles/engine.dir/src/FBOShader.cpp.o
.PHONY : src/FBOShader.cpp.o

src/FBOShader.i: src/FBOShader.cpp.i
.PHONY : src/FBOShader.i

# target to preprocess a source file
src/FBOShader.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/engine.dir/build.make CMakeFiles/engine.dir/src/FBOShader.cpp.i
.PHONY : src/FBOShader.cpp.i

src/FBOShader.s: src/FBOShader.cpp.s
.PHONY : src/FBOShader.s

# target to generate assembly for a file
src/FBOShader.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/engine.dir/build.make CMakeFiles/engine.dir/src/FBOShader.cpp.s
.PHONY : src/FBOShader.cpp.s

src/FDraw.o: src/FDraw.cpp.o
.PHONY : src/FDraw.o

# target to build an object file
src/FDraw.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/engine.dir/build.make CMakeFiles/engine.dir/src/FDraw.cpp.o
.PHONY : src/FDraw.cpp.o

src/FDraw.i: src/FDraw.cpp.i
.PHONY : src/FDraw.i

# target to preprocess a source file
src/FDraw.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/engine.dir/build.make CMakeFiles/engine.dir/src/FDraw.cpp.i
.PHONY : src/FDraw.cpp.i

src/FDraw.s: src/FDraw.cpp.s
.PHONY : src/FDraw.s

# target to generate assembly for a file
src/FDraw.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/engine.dir/build.make CMakeFiles/engine.dir/src/FDraw.cpp.s
.PHONY : src/FDraw.cpp.s

src/FNode.o: src/FNode.cpp.o
.PHONY : src/FNode.o

# target to build an object file
src/FNode.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/engine.dir/build.make CMakeFiles/engine.dir/src/FNode.cpp.o
.PHONY : src/FNode.cpp.o

src/FNode.i: src/FNode.cpp.i
.PHONY : src/FNode.i

# target to preprocess a source file
src/FNode.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/engine.dir/build.make CMakeFiles/engine.dir/src/FNode.cpp.i
.PHONY : src/FNode.cpp.i

src/FNode.s: src/FNode.cpp.s
.PHONY : src/FNode.s

# target to generate assembly for a file
src/FNode.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/engine.dir/build.make CMakeFiles/engine.dir/src/FNode.cpp.s
.PHONY : src/FNode.cpp.s

src/abs_sdl.o: src/abs_sdl.cpp.o
.PHONY : src/abs_sdl.o

# target to build an object file
src/abs_sdl.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/engine.dir/build.make CMakeFiles/engine.dir/src/abs_sdl.cpp.o
.PHONY : src/abs_sdl.cpp.o

src/abs_sdl.i: src/abs_sdl.cpp.i
.PHONY : src/abs_sdl.i

# target to preprocess a source file
src/abs_sdl.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/engine.dir/build.make CMakeFiles/engine.dir/src/abs_sdl.cpp.i
.PHONY : src/abs_sdl.cpp.i

src/abs_sdl.s: src/abs_sdl.cpp.s
.PHONY : src/abs_sdl.s

# target to generate assembly for a file
src/abs_sdl.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/engine.dir/build.make CMakeFiles/engine.dir/src/abs_sdl.cpp.s
.PHONY : src/abs_sdl.cpp.s

src/animation.o: src/animation.cpp.o
.PHONY : src/animation.o

# target to build an object file
src/animation.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/engine.dir/build.make CMakeFiles/engine.dir/src/animation.cpp.o
.PHONY : src/animation.cpp.o

src/animation.i: src/animation.cpp.i
.PHONY : src/animation.i

# target to preprocess a source file
src/animation.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/engine.dir/build.make CMakeFiles/engine.dir/src/animation.cpp.i
.PHONY : src/animation.cpp.i

src/animation.s: src/animation.cpp.s
.PHONY : src/animation.s

# target to generate assembly for a file
src/animation.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/engine.dir/build.make CMakeFiles/engine.dir/src/animation.cpp.s
.PHONY : src/animation.cpp.s

src/animator.o: src/animator.cpp.o
.PHONY : src/animator.o

# target to build an object file
src/animator.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/engine.dir/build.make CMakeFiles/engine.dir/src/animator.cpp.o
.PHONY : src/animator.cpp.o

src/animator.i: src/animator.cpp.i
.PHONY : src/animator.i

# target to preprocess a source file
src/animator.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/engine.dir/build.make CMakeFiles/engine.dir/src/animator.cpp.i
.PHONY : src/animator.cpp.i

src/animator.s: src/animator.cpp.s
.PHONY : src/animator.s

# target to generate assembly for a file
src/animator.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/engine.dir/build.make CMakeFiles/engine.dir/src/animator.cpp.s
.PHONY : src/animator.cpp.s

src/asset_manager.o: src/asset_manager.cpp.o
.PHONY : src/asset_manager.o

# target to build an object file
src/asset_manager.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/engine.dir/build.make CMakeFiles/engine.dir/src/asset_manager.cpp.o
.PHONY : src/asset_manager.cpp.o

src/asset_manager.i: src/asset_manager.cpp.i
.PHONY : src/asset_manager.i

# target to preprocess a source file
src/asset_manager.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/engine.dir/build.make CMakeFiles/engine.dir/src/asset_manager.cpp.i
.PHONY : src/asset_manager.cpp.i

src/asset_manager.s: src/asset_manager.cpp.s
.PHONY : src/asset_manager.s

# target to generate assembly for a file
src/asset_manager.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/engine.dir/build.make CMakeFiles/engine.dir/src/asset_manager.cpp.s
.PHONY : src/asset_manager.cpp.s

src/bone.o: src/bone.cpp.o
.PHONY : src/bone.o

# target to build an object file
src/bone.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/engine.dir/build.make CMakeFiles/engine.dir/src/bone.cpp.o
.PHONY : src/bone.cpp.o

src/bone.i: src/bone.cpp.i
.PHONY : src/bone.i

# target to preprocess a source file
src/bone.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/engine.dir/build.make CMakeFiles/engine.dir/src/bone.cpp.i
.PHONY : src/bone.cpp.i

src/bone.s: src/bone.cpp.s
.PHONY : src/bone.s

# target to generate assembly for a file
src/bone.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/engine.dir/build.make CMakeFiles/engine.dir/src/bone.cpp.s
.PHONY : src/bone.cpp.s

src/camera.o: src/camera.cpp.o
.PHONY : src/camera.o

# target to build an object file
src/camera.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/engine.dir/build.make CMakeFiles/engine.dir/src/camera.cpp.o
.PHONY : src/camera.cpp.o

src/camera.i: src/camera.cpp.i
.PHONY : src/camera.i

# target to preprocess a source file
src/camera.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/engine.dir/build.make CMakeFiles/engine.dir/src/camera.cpp.i
.PHONY : src/camera.cpp.i

src/camera.s: src/camera.cpp.s
.PHONY : src/camera.s

# target to generate assembly for a file
src/camera.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/engine.dir/build.make CMakeFiles/engine.dir/src/camera.cpp.s
.PHONY : src/camera.cpp.s

src/camera_node.o: src/camera_node.cpp.o
.PHONY : src/camera_node.o

# target to build an object file
src/camera_node.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/engine.dir/build.make CMakeFiles/engine.dir/src/camera_node.cpp.o
.PHONY : src/camera_node.cpp.o

src/camera_node.i: src/camera_node.cpp.i
.PHONY : src/camera_node.i

# target to preprocess a source file
src/camera_node.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/engine.dir/build.make CMakeFiles/engine.dir/src/camera_node.cpp.i
.PHONY : src/camera_node.cpp.i

src/camera_node.s: src/camera_node.cpp.s
.PHONY : src/camera_node.s

# target to generate assembly for a file
src/camera_node.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/engine.dir/build.make CMakeFiles/engine.dir/src/camera_node.cpp.s
.PHONY : src/camera_node.cpp.s

src/config.o: src/config.cpp.o
.PHONY : src/config.o

# target to build an object file
src/config.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/engine.dir/build.make CMakeFiles/engine.dir/src/config.cpp.o
.PHONY : src/config.cpp.o

src/config.i: src/config.cpp.i
.PHONY : src/config.i

# target to preprocess a source file
src/config.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/engine.dir/build.make CMakeFiles/engine.dir/src/config.cpp.i
.PHONY : src/config.cpp.i

src/config.s: src/config.cpp.s
.PHONY : src/config.s

# target to generate assembly for a file
src/config.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/engine.dir/build.make CMakeFiles/engine.dir/src/config.cpp.s
.PHONY : src/config.cpp.s

src/controler.o: src/controler.cpp.o
.PHONY : src/controler.o

# target to build an object file
src/controler.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/engine.dir/build.make CMakeFiles/engine.dir/src/controler.cpp.o
.PHONY : src/controler.cpp.o

src/controler.i: src/controler.cpp.i
.PHONY : src/controler.i

# target to preprocess a source file
src/controler.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/engine.dir/build.make CMakeFiles/engine.dir/src/controler.cpp.i
.PHONY : src/controler.cpp.i

src/controler.s: src/controler.cpp.s
.PHONY : src/controler.s

# target to generate assembly for a file
src/controler.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/engine.dir/build.make CMakeFiles/engine.dir/src/controler.cpp.s
.PHONY : src/controler.cpp.s

src/engine.o: src/engine.cpp.o
.PHONY : src/engine.o

# target to build an object file
src/engine.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/engine.dir/build.make CMakeFiles/engine.dir/src/engine.cpp.o
.PHONY : src/engine.cpp.o

src/engine.i: src/engine.cpp.i
.PHONY : src/engine.i

# target to preprocess a source file
src/engine.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/engine.dir/build.make CMakeFiles/engine.dir/src/engine.cpp.i
.PHONY : src/engine.cpp.i

src/engine.s: src/engine.cpp.s
.PHONY : src/engine.s

# target to generate assembly for a file
src/engine.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/engine.dir/build.make CMakeFiles/engine.dir/src/engine.cpp.s
.PHONY : src/engine.cpp.s

src/env.o: src/env.cpp.o
.PHONY : src/env.o

# target to build an object file
src/env.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/engine.dir/build.make CMakeFiles/engine.dir/src/env.cpp.o
.PHONY : src/env.cpp.o

src/env.i: src/env.cpp.i
.PHONY : src/env.i

# target to preprocess a source file
src/env.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/engine.dir/build.make CMakeFiles/engine.dir/src/env.cpp.i
.PHONY : src/env.cpp.i

src/env.s: src/env.cpp.s
.PHONY : src/env.s

# target to generate assembly for a file
src/env.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/engine.dir/build.make CMakeFiles/engine.dir/src/env.cpp.s
.PHONY : src/env.cpp.s

src/first_person_camera.o: src/first_person_camera.cpp.o
.PHONY : src/first_person_camera.o

# target to build an object file
src/first_person_camera.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/engine.dir/build.make CMakeFiles/engine.dir/src/first_person_camera.cpp.o
.PHONY : src/first_person_camera.cpp.o

src/first_person_camera.i: src/first_person_camera.cpp.i
.PHONY : src/first_person_camera.i

# target to preprocess a source file
src/first_person_camera.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/engine.dir/build.make CMakeFiles/engine.dir/src/first_person_camera.cpp.i
.PHONY : src/first_person_camera.cpp.i

src/first_person_camera.s: src/first_person_camera.cpp.s
.PHONY : src/first_person_camera.s

# target to generate assembly for a file
src/first_person_camera.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/engine.dir/build.make CMakeFiles/engine.dir/src/first_person_camera.cpp.s
.PHONY : src/first_person_camera.cpp.s

src/framebuffer.o: src/framebuffer.cpp.o
.PHONY : src/framebuffer.o

# target to build an object file
src/framebuffer.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/engine.dir/build.make CMakeFiles/engine.dir/src/framebuffer.cpp.o
.PHONY : src/framebuffer.cpp.o

src/framebuffer.i: src/framebuffer.cpp.i
.PHONY : src/framebuffer.i

# target to preprocess a source file
src/framebuffer.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/engine.dir/build.make CMakeFiles/engine.dir/src/framebuffer.cpp.i
.PHONY : src/framebuffer.cpp.i

src/framebuffer.s: src/framebuffer.cpp.s
.PHONY : src/framebuffer.s

# target to generate assembly for a file
src/framebuffer.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/engine.dir/build.make CMakeFiles/engine.dir/src/framebuffer.cpp.s
.PHONY : src/framebuffer.cpp.s

src/fyzika.o: src/fyzika.cpp.o
.PHONY : src/fyzika.o

# target to build an object file
src/fyzika.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/engine.dir/build.make CMakeFiles/engine.dir/src/fyzika.cpp.o
.PHONY : src/fyzika.cpp.o

src/fyzika.i: src/fyzika.cpp.i
.PHONY : src/fyzika.i

# target to preprocess a source file
src/fyzika.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/engine.dir/build.make CMakeFiles/engine.dir/src/fyzika.cpp.i
.PHONY : src/fyzika.cpp.i

src/fyzika.s: src/fyzika.cpp.s
.PHONY : src/fyzika.s

# target to generate assembly for a file
src/fyzika.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/engine.dir/build.make CMakeFiles/engine.dir/src/fyzika.cpp.s
.PHONY : src/fyzika.cpp.s

src/gui.o: src/gui.cpp.o
.PHONY : src/gui.o

# target to build an object file
src/gui.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/engine.dir/build.make CMakeFiles/engine.dir/src/gui.cpp.o
.PHONY : src/gui.cpp.o

src/gui.i: src/gui.cpp.i
.PHONY : src/gui.i

# target to preprocess a source file
src/gui.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/engine.dir/build.make CMakeFiles/engine.dir/src/gui.cpp.i
.PHONY : src/gui.cpp.i

src/gui.s: src/gui.cpp.s
.PHONY : src/gui.s

# target to generate assembly for a file
src/gui.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/engine.dir/build.make CMakeFiles/engine.dir/src/gui.cpp.s
.PHONY : src/gui.cpp.s

src/lights.o: src/lights.cpp.o
.PHONY : src/lights.o

# target to build an object file
src/lights.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/engine.dir/build.make CMakeFiles/engine.dir/src/lights.cpp.o
.PHONY : src/lights.cpp.o

src/lights.i: src/lights.cpp.i
.PHONY : src/lights.i

# target to preprocess a source file
src/lights.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/engine.dir/build.make CMakeFiles/engine.dir/src/lights.cpp.i
.PHONY : src/lights.cpp.i

src/lights.s: src/lights.cpp.s
.PHONY : src/lights.s

# target to generate assembly for a file
src/lights.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/engine.dir/build.make CMakeFiles/engine.dir/src/lights.cpp.s
.PHONY : src/lights.cpp.s

src/main.o: src/main.cpp.o
.PHONY : src/main.o

# target to build an object file
src/main.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/engine.dir/build.make CMakeFiles/engine.dir/src/main.cpp.o
.PHONY : src/main.cpp.o

src/main.i: src/main.cpp.i
.PHONY : src/main.i

# target to preprocess a source file
src/main.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/engine.dir/build.make CMakeFiles/engine.dir/src/main.cpp.i
.PHONY : src/main.cpp.i

src/main.s: src/main.cpp.s
.PHONY : src/main.s

# target to generate assembly for a file
src/main.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/engine.dir/build.make CMakeFiles/engine.dir/src/main.cpp.s
.PHONY : src/main.cpp.s

src/material.o: src/material.cpp.o
.PHONY : src/material.o

# target to build an object file
src/material.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/engine.dir/build.make CMakeFiles/engine.dir/src/material.cpp.o
.PHONY : src/material.cpp.o

src/material.i: src/material.cpp.i
.PHONY : src/material.i

# target to preprocess a source file
src/material.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/engine.dir/build.make CMakeFiles/engine.dir/src/material.cpp.i
.PHONY : src/material.cpp.i

src/material.s: src/material.cpp.s
.PHONY : src/material.s

# target to generate assembly for a file
src/material.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/engine.dir/build.make CMakeFiles/engine.dir/src/material.cpp.s
.PHONY : src/material.cpp.s

src/mesh.o: src/mesh.cpp.o
.PHONY : src/mesh.o

# target to build an object file
src/mesh.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/engine.dir/build.make CMakeFiles/engine.dir/src/mesh.cpp.o
.PHONY : src/mesh.cpp.o

src/mesh.i: src/mesh.cpp.i
.PHONY : src/mesh.i

# target to preprocess a source file
src/mesh.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/engine.dir/build.make CMakeFiles/engine.dir/src/mesh.cpp.i
.PHONY : src/mesh.cpp.i

src/mesh.s: src/mesh.cpp.s
.PHONY : src/mesh.s

# target to generate assembly for a file
src/mesh.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/engine.dir/build.make CMakeFiles/engine.dir/src/mesh.cpp.s
.PHONY : src/mesh.cpp.s

src/mesh_node.o: src/mesh_node.cpp.o
.PHONY : src/mesh_node.o

# target to build an object file
src/mesh_node.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/engine.dir/build.make CMakeFiles/engine.dir/src/mesh_node.cpp.o
.PHONY : src/mesh_node.cpp.o

src/mesh_node.i: src/mesh_node.cpp.i
.PHONY : src/mesh_node.i

# target to preprocess a source file
src/mesh_node.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/engine.dir/build.make CMakeFiles/engine.dir/src/mesh_node.cpp.i
.PHONY : src/mesh_node.cpp.i

src/mesh_node.s: src/mesh_node.cpp.s
.PHONY : src/mesh_node.s

# target to generate assembly for a file
src/mesh_node.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/engine.dir/build.make CMakeFiles/engine.dir/src/mesh_node.cpp.s
.PHONY : src/mesh_node.cpp.s

src/model.o: src/model.cpp.o
.PHONY : src/model.o

# target to build an object file
src/model.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/engine.dir/build.make CMakeFiles/engine.dir/src/model.cpp.o
.PHONY : src/model.cpp.o

src/model.i: src/model.cpp.i
.PHONY : src/model.i

# target to preprocess a source file
src/model.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/engine.dir/build.make CMakeFiles/engine.dir/src/model.cpp.i
.PHONY : src/model.cpp.i

src/model.s: src/model.cpp.s
.PHONY : src/model.s

# target to generate assembly for a file
src/model.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/engine.dir/build.make CMakeFiles/engine.dir/src/model.cpp.s
.PHONY : src/model.cpp.s

src/model_node.o: src/model_node.cpp.o
.PHONY : src/model_node.o

# target to build an object file
src/model_node.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/engine.dir/build.make CMakeFiles/engine.dir/src/model_node.cpp.o
.PHONY : src/model_node.cpp.o

src/model_node.i: src/model_node.cpp.i
.PHONY : src/model_node.i

# target to preprocess a source file
src/model_node.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/engine.dir/build.make CMakeFiles/engine.dir/src/model_node.cpp.i
.PHONY : src/model_node.cpp.i

src/model_node.s: src/model_node.cpp.s
.PHONY : src/model_node.s

# target to generate assembly for a file
src/model_node.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/engine.dir/build.make CMakeFiles/engine.dir/src/model_node.cpp.s
.PHONY : src/model_node.cpp.s

src/node.o: src/node.cpp.o
.PHONY : src/node.o

# target to build an object file
src/node.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/engine.dir/build.make CMakeFiles/engine.dir/src/node.cpp.o
.PHONY : src/node.cpp.o

src/node.i: src/node.cpp.i
.PHONY : src/node.i

# target to preprocess a source file
src/node.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/engine.dir/build.make CMakeFiles/engine.dir/src/node.cpp.i
.PHONY : src/node.cpp.i

src/node.s: src/node.cpp.s
.PHONY : src/node.s

# target to generate assembly for a file
src/node.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/engine.dir/build.make CMakeFiles/engine.dir/src/node.cpp.s
.PHONY : src/node.cpp.s

src/orbit_camera.o: src/orbit_camera.cpp.o
.PHONY : src/orbit_camera.o

# target to build an object file
src/orbit_camera.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/engine.dir/build.make CMakeFiles/engine.dir/src/orbit_camera.cpp.o
.PHONY : src/orbit_camera.cpp.o

src/orbit_camera.i: src/orbit_camera.cpp.i
.PHONY : src/orbit_camera.i

# target to preprocess a source file
src/orbit_camera.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/engine.dir/build.make CMakeFiles/engine.dir/src/orbit_camera.cpp.i
.PHONY : src/orbit_camera.cpp.i

src/orbit_camera.s: src/orbit_camera.cpp.s
.PHONY : src/orbit_camera.s

# target to generate assembly for a file
src/orbit_camera.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/engine.dir/build.make CMakeFiles/engine.dir/src/orbit_camera.cpp.s
.PHONY : src/orbit_camera.cpp.s

src/player_con.o: src/player_con.cpp.o
.PHONY : src/player_con.o

# target to build an object file
src/player_con.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/engine.dir/build.make CMakeFiles/engine.dir/src/player_con.cpp.o
.PHONY : src/player_con.cpp.o

src/player_con.i: src/player_con.cpp.i
.PHONY : src/player_con.i

# target to preprocess a source file
src/player_con.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/engine.dir/build.make CMakeFiles/engine.dir/src/player_con.cpp.i
.PHONY : src/player_con.cpp.i

src/player_con.s: src/player_con.cpp.s
.PHONY : src/player_con.s

# target to generate assembly for a file
src/player_con.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/engine.dir/build.make CMakeFiles/engine.dir/src/player_con.cpp.s
.PHONY : src/player_con.cpp.s

src/renderer.o: src/renderer.cpp.o
.PHONY : src/renderer.o

# target to build an object file
src/renderer.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/engine.dir/build.make CMakeFiles/engine.dir/src/renderer.cpp.o
.PHONY : src/renderer.cpp.o

src/renderer.i: src/renderer.cpp.i
.PHONY : src/renderer.i

# target to preprocess a source file
src/renderer.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/engine.dir/build.make CMakeFiles/engine.dir/src/renderer.cpp.i
.PHONY : src/renderer.cpp.i

src/renderer.s: src/renderer.cpp.s
.PHONY : src/renderer.s

# target to generate assembly for a file
src/renderer.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/engine.dir/build.make CMakeFiles/engine.dir/src/renderer.cpp.s
.PHONY : src/renderer.cpp.s

src/scene.o: src/scene.cpp.o
.PHONY : src/scene.o

# target to build an object file
src/scene.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/engine.dir/build.make CMakeFiles/engine.dir/src/scene.cpp.o
.PHONY : src/scene.cpp.o

src/scene.i: src/scene.cpp.i
.PHONY : src/scene.i

# target to preprocess a source file
src/scene.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/engine.dir/build.make CMakeFiles/engine.dir/src/scene.cpp.i
.PHONY : src/scene.cpp.i

src/scene.s: src/scene.cpp.s
.PHONY : src/scene.s

# target to generate assembly for a file
src/scene.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/engine.dir/build.make CMakeFiles/engine.dir/src/scene.cpp.s
.PHONY : src/scene.cpp.s

src/shader.o: src/shader.cpp.o
.PHONY : src/shader.o

# target to build an object file
src/shader.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/engine.dir/build.make CMakeFiles/engine.dir/src/shader.cpp.o
.PHONY : src/shader.cpp.o

src/shader.i: src/shader.cpp.i
.PHONY : src/shader.i

# target to preprocess a source file
src/shader.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/engine.dir/build.make CMakeFiles/engine.dir/src/shader.cpp.i
.PHONY : src/shader.cpp.i

src/shader.s: src/shader.cpp.s
.PHONY : src/shader.s

# target to generate assembly for a file
src/shader.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/engine.dir/build.make CMakeFiles/engine.dir/src/shader.cpp.s
.PHONY : src/shader.cpp.s

src/transform.o: src/transform.cpp.o
.PHONY : src/transform.o

# target to build an object file
src/transform.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/engine.dir/build.make CMakeFiles/engine.dir/src/transform.cpp.o
.PHONY : src/transform.cpp.o

src/transform.i: src/transform.cpp.i
.PHONY : src/transform.i

# target to preprocess a source file
src/transform.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/engine.dir/build.make CMakeFiles/engine.dir/src/transform.cpp.i
.PHONY : src/transform.cpp.i

src/transform.s: src/transform.cpp.s
.PHONY : src/transform.s

# target to generate assembly for a file
src/transform.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/engine.dir/build.make CMakeFiles/engine.dir/src/transform.cpp.s
.PHONY : src/transform.cpp.s

third_party/imgui/backends/imgui_impl_opengl3.o: third_party/imgui/backends/imgui_impl_opengl3.cpp.o
.PHONY : third_party/imgui/backends/imgui_impl_opengl3.o

# target to build an object file
third_party/imgui/backends/imgui_impl_opengl3.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/engine.dir/build.make CMakeFiles/engine.dir/third_party/imgui/backends/imgui_impl_opengl3.cpp.o
.PHONY : third_party/imgui/backends/imgui_impl_opengl3.cpp.o

third_party/imgui/backends/imgui_impl_opengl3.i: third_party/imgui/backends/imgui_impl_opengl3.cpp.i
.PHONY : third_party/imgui/backends/imgui_impl_opengl3.i

# target to preprocess a source file
third_party/imgui/backends/imgui_impl_opengl3.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/engine.dir/build.make CMakeFiles/engine.dir/third_party/imgui/backends/imgui_impl_opengl3.cpp.i
.PHONY : third_party/imgui/backends/imgui_impl_opengl3.cpp.i

third_party/imgui/backends/imgui_impl_opengl3.s: third_party/imgui/backends/imgui_impl_opengl3.cpp.s
.PHONY : third_party/imgui/backends/imgui_impl_opengl3.s

# target to generate assembly for a file
third_party/imgui/backends/imgui_impl_opengl3.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/engine.dir/build.make CMakeFiles/engine.dir/third_party/imgui/backends/imgui_impl_opengl3.cpp.s
.PHONY : third_party/imgui/backends/imgui_impl_opengl3.cpp.s

third_party/imgui/backends/imgui_impl_sdl.o: third_party/imgui/backends/imgui_impl_sdl.cpp.o
.PHONY : third_party/imgui/backends/imgui_impl_sdl.o

# target to build an object file
third_party/imgui/backends/imgui_impl_sdl.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/engine.dir/build.make CMakeFiles/engine.dir/third_party/imgui/backends/imgui_impl_sdl.cpp.o
.PHONY : third_party/imgui/backends/imgui_impl_sdl.cpp.o

third_party/imgui/backends/imgui_impl_sdl.i: third_party/imgui/backends/imgui_impl_sdl.cpp.i
.PHONY : third_party/imgui/backends/imgui_impl_sdl.i

# target to preprocess a source file
third_party/imgui/backends/imgui_impl_sdl.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/engine.dir/build.make CMakeFiles/engine.dir/third_party/imgui/backends/imgui_impl_sdl.cpp.i
.PHONY : third_party/imgui/backends/imgui_impl_sdl.cpp.i

third_party/imgui/backends/imgui_impl_sdl.s: third_party/imgui/backends/imgui_impl_sdl.cpp.s
.PHONY : third_party/imgui/backends/imgui_impl_sdl.s

# target to generate assembly for a file
third_party/imgui/backends/imgui_impl_sdl.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/engine.dir/build.make CMakeFiles/engine.dir/third_party/imgui/backends/imgui_impl_sdl.cpp.s
.PHONY : third_party/imgui/backends/imgui_impl_sdl.cpp.s

third_party/imgui/imgui.o: third_party/imgui/imgui.cpp.o
.PHONY : third_party/imgui/imgui.o

# target to build an object file
third_party/imgui/imgui.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/engine.dir/build.make CMakeFiles/engine.dir/third_party/imgui/imgui.cpp.o
.PHONY : third_party/imgui/imgui.cpp.o

third_party/imgui/imgui.i: third_party/imgui/imgui.cpp.i
.PHONY : third_party/imgui/imgui.i

# target to preprocess a source file
third_party/imgui/imgui.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/engine.dir/build.make CMakeFiles/engine.dir/third_party/imgui/imgui.cpp.i
.PHONY : third_party/imgui/imgui.cpp.i

third_party/imgui/imgui.s: third_party/imgui/imgui.cpp.s
.PHONY : third_party/imgui/imgui.s

# target to generate assembly for a file
third_party/imgui/imgui.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/engine.dir/build.make CMakeFiles/engine.dir/third_party/imgui/imgui.cpp.s
.PHONY : third_party/imgui/imgui.cpp.s

third_party/imgui/imgui_draw.o: third_party/imgui/imgui_draw.cpp.o
.PHONY : third_party/imgui/imgui_draw.o

# target to build an object file
third_party/imgui/imgui_draw.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/engine.dir/build.make CMakeFiles/engine.dir/third_party/imgui/imgui_draw.cpp.o
.PHONY : third_party/imgui/imgui_draw.cpp.o

third_party/imgui/imgui_draw.i: third_party/imgui/imgui_draw.cpp.i
.PHONY : third_party/imgui/imgui_draw.i

# target to preprocess a source file
third_party/imgui/imgui_draw.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/engine.dir/build.make CMakeFiles/engine.dir/third_party/imgui/imgui_draw.cpp.i
.PHONY : third_party/imgui/imgui_draw.cpp.i

third_party/imgui/imgui_draw.s: third_party/imgui/imgui_draw.cpp.s
.PHONY : third_party/imgui/imgui_draw.s

# target to generate assembly for a file
third_party/imgui/imgui_draw.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/engine.dir/build.make CMakeFiles/engine.dir/third_party/imgui/imgui_draw.cpp.s
.PHONY : third_party/imgui/imgui_draw.cpp.s

third_party/imgui/imgui_tables.o: third_party/imgui/imgui_tables.cpp.o
.PHONY : third_party/imgui/imgui_tables.o

# target to build an object file
third_party/imgui/imgui_tables.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/engine.dir/build.make CMakeFiles/engine.dir/third_party/imgui/imgui_tables.cpp.o
.PHONY : third_party/imgui/imgui_tables.cpp.o

third_party/imgui/imgui_tables.i: third_party/imgui/imgui_tables.cpp.i
.PHONY : third_party/imgui/imgui_tables.i

# target to preprocess a source file
third_party/imgui/imgui_tables.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/engine.dir/build.make CMakeFiles/engine.dir/third_party/imgui/imgui_tables.cpp.i
.PHONY : third_party/imgui/imgui_tables.cpp.i

third_party/imgui/imgui_tables.s: third_party/imgui/imgui_tables.cpp.s
.PHONY : third_party/imgui/imgui_tables.s

# target to generate assembly for a file
third_party/imgui/imgui_tables.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/engine.dir/build.make CMakeFiles/engine.dir/third_party/imgui/imgui_tables.cpp.s
.PHONY : third_party/imgui/imgui_tables.cpp.s

third_party/imgui/imgui_widgets.o: third_party/imgui/imgui_widgets.cpp.o
.PHONY : third_party/imgui/imgui_widgets.o

# target to build an object file
third_party/imgui/imgui_widgets.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/engine.dir/build.make CMakeFiles/engine.dir/third_party/imgui/imgui_widgets.cpp.o
.PHONY : third_party/imgui/imgui_widgets.cpp.o

third_party/imgui/imgui_widgets.i: third_party/imgui/imgui_widgets.cpp.i
.PHONY : third_party/imgui/imgui_widgets.i

# target to preprocess a source file
third_party/imgui/imgui_widgets.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/engine.dir/build.make CMakeFiles/engine.dir/third_party/imgui/imgui_widgets.cpp.i
.PHONY : third_party/imgui/imgui_widgets.cpp.i

third_party/imgui/imgui_widgets.s: third_party/imgui/imgui_widgets.cpp.s
.PHONY : third_party/imgui/imgui_widgets.s

# target to generate assembly for a file
third_party/imgui/imgui_widgets.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/engine.dir/build.make CMakeFiles/engine.dir/third_party/imgui/imgui_widgets.cpp.s
.PHONY : third_party/imgui/imgui_widgets.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... engine"
	@echo "... src/FBOShader.o"
	@echo "... src/FBOShader.i"
	@echo "... src/FBOShader.s"
	@echo "... src/FDraw.o"
	@echo "... src/FDraw.i"
	@echo "... src/FDraw.s"
	@echo "... src/FNode.o"
	@echo "... src/FNode.i"
	@echo "... src/FNode.s"
	@echo "... src/abs_sdl.o"
	@echo "... src/abs_sdl.i"
	@echo "... src/abs_sdl.s"
	@echo "... src/animation.o"
	@echo "... src/animation.i"
	@echo "... src/animation.s"
	@echo "... src/animator.o"
	@echo "... src/animator.i"
	@echo "... src/animator.s"
	@echo "... src/asset_manager.o"
	@echo "... src/asset_manager.i"
	@echo "... src/asset_manager.s"
	@echo "... src/bone.o"
	@echo "... src/bone.i"
	@echo "... src/bone.s"
	@echo "... src/camera.o"
	@echo "... src/camera.i"
	@echo "... src/camera.s"
	@echo "... src/camera_node.o"
	@echo "... src/camera_node.i"
	@echo "... src/camera_node.s"
	@echo "... src/config.o"
	@echo "... src/config.i"
	@echo "... src/config.s"
	@echo "... src/controler.o"
	@echo "... src/controler.i"
	@echo "... src/controler.s"
	@echo "... src/engine.o"
	@echo "... src/engine.i"
	@echo "... src/engine.s"
	@echo "... src/env.o"
	@echo "... src/env.i"
	@echo "... src/env.s"
	@echo "... src/first_person_camera.o"
	@echo "... src/first_person_camera.i"
	@echo "... src/first_person_camera.s"
	@echo "... src/framebuffer.o"
	@echo "... src/framebuffer.i"
	@echo "... src/framebuffer.s"
	@echo "... src/fyzika.o"
	@echo "... src/fyzika.i"
	@echo "... src/fyzika.s"
	@echo "... src/gui.o"
	@echo "... src/gui.i"
	@echo "... src/gui.s"
	@echo "... src/lights.o"
	@echo "... src/lights.i"
	@echo "... src/lights.s"
	@echo "... src/main.o"
	@echo "... src/main.i"
	@echo "... src/main.s"
	@echo "... src/material.o"
	@echo "... src/material.i"
	@echo "... src/material.s"
	@echo "... src/mesh.o"
	@echo "... src/mesh.i"
	@echo "... src/mesh.s"
	@echo "... src/mesh_node.o"
	@echo "... src/mesh_node.i"
	@echo "... src/mesh_node.s"
	@echo "... src/model.o"
	@echo "... src/model.i"
	@echo "... src/model.s"
	@echo "... src/model_node.o"
	@echo "... src/model_node.i"
	@echo "... src/model_node.s"
	@echo "... src/node.o"
	@echo "... src/node.i"
	@echo "... src/node.s"
	@echo "... src/orbit_camera.o"
	@echo "... src/orbit_camera.i"
	@echo "... src/orbit_camera.s"
	@echo "... src/player_con.o"
	@echo "... src/player_con.i"
	@echo "... src/player_con.s"
	@echo "... src/renderer.o"
	@echo "... src/renderer.i"
	@echo "... src/renderer.s"
	@echo "... src/scene.o"
	@echo "... src/scene.i"
	@echo "... src/scene.s"
	@echo "... src/shader.o"
	@echo "... src/shader.i"
	@echo "... src/shader.s"
	@echo "... src/transform.o"
	@echo "... src/transform.i"
	@echo "... src/transform.s"
	@echo "... third_party/imgui/backends/imgui_impl_opengl3.o"
	@echo "... third_party/imgui/backends/imgui_impl_opengl3.i"
	@echo "... third_party/imgui/backends/imgui_impl_opengl3.s"
	@echo "... third_party/imgui/backends/imgui_impl_sdl.o"
	@echo "... third_party/imgui/backends/imgui_impl_sdl.i"
	@echo "... third_party/imgui/backends/imgui_impl_sdl.s"
	@echo "... third_party/imgui/imgui.o"
	@echo "... third_party/imgui/imgui.i"
	@echo "... third_party/imgui/imgui.s"
	@echo "... third_party/imgui/imgui_draw.o"
	@echo "... third_party/imgui/imgui_draw.i"
	@echo "... third_party/imgui/imgui_draw.s"
	@echo "... third_party/imgui/imgui_tables.o"
	@echo "... third_party/imgui/imgui_tables.i"
	@echo "... third_party/imgui/imgui_tables.s"
	@echo "... third_party/imgui/imgui_widgets.o"
	@echo "... third_party/imgui/imgui_widgets.i"
	@echo "... third_party/imgui/imgui_widgets.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

